@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGQyOTU1ZWRkNWMxYjUzMGFlYjhmZmYiLCJ1c2VyVHlwZSI6ImRyaXZlciIsImlhdCI6MTc1ODcxNDg0NiwiZXhwIjoxNzkwMjUwODQ2fQ.E_iTbxXaYYum_UU778b5Pxmva75wrVqSeIEQfeyL5Yw
# @url =  http://localhost:4567
@url =  http://192.168.1.43:4567

//Register for client
###
GET {{url}}/api/v1/driver/getCityList HTTP/1.1
Content-type: application/json


//Register for client
###
POST {{url}}/api/v1/driver/register HTTP/1.1
Content-type: application/json

{
    "firstName": "User",
    "lastName": "Test",
    "email": "user09@gmail.com",
    "phone": "99999999991",
    "cityId": "68c80a5f57d04cb8377ba0ab",
    "deviceId": "abcdef",
    "refByCode": "",
    "password": "123456"
}


//registerVerify
###
POST {{url}}/api/v1/driver/registerVerify HTTP/1.1
Content-type: application/json

{
    "token": "WLN7LDMOSZWic2jpaDy767NhSE7Egu79MAZdQPKZ",
    "otp": "123456"
}

//login
###
POST {{url}}/api/v1/driver/login HTTP/1.1
Content-type: application/json

{
    "loginType": "user0001@gmail.com",
    "password": "123456"
}

//verifyUser
###
POST {{url}}/api/v1/driver/verifyUser HTTP/1.1
Content-type: application/json

{
    "token": "J22X7Fqqm7bWPAQLRPesXahUIFuqyDdZABjDV4FT",
    "otp": "123456"
}

//forgotPassword
###
POST {{url}}/api/v1/driver/forgotPassword HTTP/1.1
Content-type: application/json

{
    "loginType": "raja.shakur@example.com"
}

//forgotPasswordVerify
###
POST {{url}}/api/v1/driver/forgotPasswordVerify HTTP/1.1
Content-type: application/json

{
    "token": "gXFwRNGgLcGgKv7Jel6WLjKyvOLRXhTK3X6089rW",
    "otp": "123456",
    "newPassword": "12345678",
    "confirmPassword": "12345678"
}

//getDriverProfile
###
GET {{url}}/api/v1/driver/getDriverProfile HTTP/1.1
Content-type: application/json
Authorization: {{token}}

//updateProfileImage
###
POST {{url}}/api/v1/driver/updateProfileImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "image": "https://www.example.com/identityFront.jpg"
}

//saveDriverDocuments
###
POST {{url}}/api/v1/driver/saveDriverDocuments HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "identityFront": "https://www.example.com/identityFront.jpg",
    "identityBack": "https://www.example.com/identityBack.jpg"
}



//getVehicleType
###
GET {{url}}/api/v1/driver/getVehicleType HTTP/1.1
Content-type: application/json
Authorization: {{token}}


//addNewVehicle
###
POST {{url}}/api/v1/driver/addNewVehicle HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "vehicle": "68cd3a49f084b50e06c9de26",
    "numberPlate": "ABC123",
    "model": "Yamaha ZN",
    "capacityWeight": 1000,
    "capacityVolume": 100
}

//updateVehicleStatus
###
POST {{url}}/api/v1/driver/updateVehicleStatus HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "vehicleId": "68ca8e88f9eeb3a8c922cda7"
}


//deliveryPickupReached
###
POST {{url}}/api/v1/driver/deliveryPickupReached HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGY4N2MzYjQwOTM4ZDRkMmYyZWIzNDEiLCJ1c2VyVHlwZSI6ImRyaXZlciIsImlhdCI6MTc2MTI5OTk1MSwiZXhwIjoxNzkyODM1OTUxfQ.fY-kEztYFyJeG0lunH-QisK4srjv2EyuYm6Rloph3pM

{
    "txId": ""
}


//deliveryOnGoingReached
###
POST {{url}}/api/v1/driver/deliveryOnGoingReached HTTP/1.1
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGY4N2MzYjQwOTM4ZDRkMmYyZWIzNDEiLCJ1c2VyVHlwZSI6ImRyaXZlciIsImlhdCI6MTc2MTI5OTk1MSwiZXhwIjoxNzkyODM1OTUxfQ.fY-kEztYFyJeG0lunH-QisK4srjv2EyuYm6Rloph3pM


{
    "txId": "",
    "otp": ""
}



//deliveryCancelledByDriver
###
POST {{url}}/api/v1/driver/deliveryCancelledByDriver HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "txId": "1234567890",
    "cancellationReason": "Changed my mind"
}


//deliveryCompleted
###
POST {{url}}/api/v1/driver/deliveryCompleted HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "txId": "TXN1761386723727894",
    "image": "https://www.example.com/deliveryCompleted.jpg"
}


//updateProfileImage
###
POST {{url}}/api/v1/driver/updateProfileImage HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "image": "https://www.example.com/identityFront.jpg"
}


//createTicket
###
POST {{url}}/api/v1/ticket/createTicket HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "subject": "dafsdf",
    "description": "description"
}

//getTicketList
###
POST {{url}}/api/v1/ticket/getTicketList HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "keyWord": "",
    "pageNo": 1,
    "size": 10
}

//getTicketById
###
POST {{url}}/api/v1/ticket/getTicketById HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "id": "69083cc8dd887949c4e9ec6a"
}

//ticketReply
###
POST {{url}}/api/v1/ticket/ticketReply HTTP/1.1
Content-type: application/json
Authorization: {{token}}

{
    "message": "hi",
    "ticketId": "69083cc8dd887949c4e9ec6a"
}